### ISSUE TITLE
Get Raw Data  

### ISSUE THREAD

**Issue by LiCong2016** [Maicius/UserBehavior#4]
你好，天池下载数据需要报名，可是比赛报名结束了。源数据可以提供一份给我吗？
如果可以，发一份到我邮箱：XXXX; 或者百度网盘共享一下。
感激不尽！

**Comment by Maicius** [comment]
文件列表已经加到项目中了，在raw_data中，可以直接点这个链接：
https://github.com/Maicius/UserBehavior/blob/master/raw_data/ECommAI_UBD_data_list_20190703.txt

**Comment by Cong-Lee** [comment]
谢谢啦！
